/**
 * Profiles.
 *
 * Lets a family share one device: each person — a parent included — gets
 * their own name, avatar, and age, and their own separate stars, adaptive
 * levels, and settings (see `AppProvider`, which keys progress/settings/
 * usage/freshness by profile id). Switching or managing profiles always sits
 * behind the parent gate (`ParentGateModal`) — a child should never be able
 * to hand themselves an adult's profile, or an older sibling's, without a
 * grown-up saying so.
 *
 * Deliberately no free-text name entry: picking from a fixed list plus an
 * avatar keeps the "collect nothing" promise literal — there is no keyboard
 * input anywhere in this file's flow, so there is nothing typed to even
 * consider sensitive.
 */

export type Profile = {
  readonly id: string;
  readonly name: string;
  readonly avatar: string;
  /** Actual age in years — see `catalog.ts`'s `minAge`/`maxAge`, which this
   *  is compared against directly. No age "groups" or bands: a game shows or
   *  doesn't based on this exact number. */
  readonly age: number;
};

export const MIN_AGE = 1;
export const MAX_AGE = 99;
export const DEFAULT_AGE = 6;

export const NAME_CHOICES: readonly string[] = [
  'Explorer',
  'Star',
  'Champ',
  'Buddy',
  'Sunshine',
  'Tiger',
  'Rocket',
  'Sparkle',
  'Chief',
  'Robin',
];

export const AVATAR_CHOICES: readonly string[] = [
  '🧒',
  '👦',
  '👧',
  '🧑',
  '👩',
  '👨',
  '🧓',
  '😀',
  '🐱',
  '🦁',
  '🦄',
  '🌟',
];

export const DEFAULT_NAME: string = NAME_CHOICES[0];
export const DEFAULT_AVATAR: string = AVATAR_CHOICES[0];

export function clampAge(age: number): number {
  return Math.max(MIN_AGE, Math.min(MAX_AGE, Math.round(age)));
}

export type ProfilesState = {
  readonly profiles: readonly Profile[];
  readonly activeProfileId: string | null;
};

export const EMPTY_PROFILES: ProfilesState = { profiles: [], activeProfileId: null };

export type ProfileInput = {
  readonly name: string;
  readonly avatar: string;
  readonly age: number;
};

/** The profile currently in control. Falls back to the first profile in the
 *  list if `activeProfileId` doesn't (yet, or any longer) point at a real
 *  one, so the app is never left with no one selected while any profile
 *  exists. */
export function getActiveProfile(state: ProfilesState): Profile | null {
  return state.profiles.find((p) => p.id === state.activeProfileId) ?? state.profiles[0] ?? null;
}

/** `id` is generated by the caller (see `AppProvider`) — this stays pure so
 *  every rule about the resulting list can be tested without an id source. */
export function addProfile(state: ProfilesState, input: ProfileInput, id: string): ProfilesState {
  const profile: Profile = { id, name: input.name, avatar: input.avatar, age: clampAge(input.age) };
  return {
    profiles: [...state.profiles, profile],
    // The very first profile created becomes active automatically — there is
    // no meaningful "which one is active" question with only one profile.
    activeProfileId: state.activeProfileId ?? profile.id,
  };
}

export function updateProfile(
  state: ProfilesState,
  id: string,
  patch: Partial<ProfileInput>,
): ProfilesState {
  return {
    ...state,
    profiles: state.profiles.map((p) =>
      p.id === id
        ? { ...p, ...patch, age: patch.age != null ? clampAge(patch.age) : p.age }
        : p,
    ),
  };
}

/** Removing the active profile hands control to whichever profile is now
 *  first, if any remain — never leaves a dangling id pointing at nothing. */
export function removeProfile(state: ProfilesState, id: string): ProfilesState {
  const profiles = state.profiles.filter((p) => p.id !== id);
  const activeProfileId = state.activeProfileId === id ? (profiles[0]?.id ?? null) : state.activeProfileId;
  return { profiles, activeProfileId };
}

/** Switching to an id that isn't in the list is a no-op rather than an
 *  error — the caller (a profile picker rendered from this same list) can't
 *  actually offer an id that doesn't exist, but staying a no-op means a
 *  stale closure can never corrupt state. */
export function switchProfile(state: ProfilesState, id: string): ProfilesState {
  if (!state.profiles.some((p) => p.id === id)) return state;
  return { ...state, activeProfileId: id };
}
