/**
 * Word Ladder's words, chosen by hand.
 *
 * Every word a player sees in Word Ladder comes from these two lists — the
 * rungs, the right answers and the wrong ones alike. Nothing is generated by
 * changing letters, which is how a word game ends up showing a child a word
 * nobody picked.
 *
 * The rule for being on a list: an everyday word a ten-year-old reads, that
 * a parent would be happy to see on screen. So no swearing or slang, no
 * insults, nothing about weapons, drink, drugs, violence or bodies, and no
 * word that is innocent in itself but best known as something else. Mostly
 * plain nouns and verbs. When in doubt, a word was left out: a thinner list
 * only means fewer ladders, and there are plenty.
 */

export const THREE: readonly string[] = `
ace act add age ago aid aim air all and ant any ape apt arc ark arm art ash ask ate awe axe
bad bag ban bar bat bay bed bee beg bet bib bid big bin bit bog box boy bud bug bun bus but buy
cab can cap car cat cod cog cot cow cry cub cup cut
dad dam day den dew did dig dim dip dog dot dry dug duo dye
ear eat egg elf elk elm end eve eye
fan far fed fee few fig fin fir fit fix fly foe fog for fox fry fun fur
gap gas gel gem get gnu got gum guy gym
had ham has hat hay hen her hid him hip his hit hop hot how hub hue hug hum hut
ice icy ink inn its ivy
jam jar jaw jet jig job jog jot joy jug
keg key kid kin kit
lab lad lag lap law lay led leg let lid lie lip lit log lot low
mad man map mat may men met mix mob mom mop mud mug mum
nag nap net new nip nod nor not now nut
oak oar oat odd off oil old one orb ore our out owl own
pad pal pan paw pay pea peg pen pet pie pig pin pit pod pop pot pro pug pun pup put
rag ram ran rap rat raw ray red rib rid rig rim rip rod rot row rub rug run rye
sad sap sat saw say sea see set sew shy sip sir sit six ski sky sly sob son sow soy spa spy sub sum sun
tab tag tan tap tar tax tea ten the tie tin tip toe ton too top tow toy try tub tug two
urn use
van vat vet vow
wag wax way web wed wet who why wig win wit wok won wow
yak yam yap yes yet yew you
zap zip zoo
`
  .split(/\s+/)
  .filter(Boolean);

export const FOUR: readonly string[] = `
able ache acid acre aged also arch area aunt away
baby back bake bald ball band bank bare bark barn base bath bead beak beam bean bear beat bell belt bend
bent best bike bill bind bird bite blew blow blue blur boat body boil bold bolt bond bone book boot bore
born boss both bowl bulb bump bunk burn bush busy
cage cake calf call calm came camp cane cape card care cart case cash cast cave cell chat chew chin chip
chop city clap claw clay clip club clue coal coat code coin cold colt comb come cone cook cool cope copy
cord core corn cost crab crew crop crow cube cure curl cute
damp dare dark dart dash date dawn deal dear deck deep deer desk dial dice dine dirt dish dive dock dome
done door dose dove down drag draw drew drip drop drum duck dull dune dusk dust duty
each earn ease east easy edge else even ever exit
face fact fade fail fair fall fame farm fast fate fear feed feel feet fell felt fern file fill film find
fine fire firm fish five flag flap flat flew flip flow foal foam fold folk fond food foot fork form fort
four free frog from fuel full fund fuse
gain game gate gave gaze gear gift give glad glow glue goal goat gold golf gone good gown grab grew grey
grin grip grow gulp
hail hair half hall halt hand hang hard hare harp have hawk head heal heap hear heat heel held helm help
herb herd here hero hide high hike hill hint hive hold hole home hood hook hoop hope horn hose host hour
huge hush
idea inch into iron item
join joke jump just
keen keep kept kick kind king kite knee knew knit knot know
lace lack lady laid lake lamb lamp land lane last late lawn lazy lead leaf leak lean leap left lend lens
less lick lift like lily lime line link lion list live load loaf loan lock loft long look loop lose loss
lost loud love luck lump
made mail main make mane many mare mark mask mast mate maze meal mean meat meet melt menu mere mess mice
mild milk mill mind mine mint miss mist mole moon more moss most moth move much mule must
nail name near neat neck need nest news next nice nine none noon nose note
once only open oven over
pace pack page paid pail pair pale palm pane park part pass past path peak pear peel peer pest pick pier
pile pine pink pipe plan play plot plug plum poem poet pole pond pony pool poor port pose post pour pull
pump pure push
race rack raft rail rain rake ramp rang rank rare rate read real rear rest rice rich ride ring rink ripe
rise risk road roam roar robe rock rode role roll roof room root rope rose rosy rule rung rush rust
safe sage said sail sake salt same sand sang sank save seal seam seat seed seek seem seen sell send sent
shed ship shoe shop show shut side sigh sign silk sing sink site size skip slab sled slid slim slip slot
slow snow soak soap soar sock sofa soft soil sold sole some song soon sort soup sour spin spot star stay
stem step stir stop such suit sung sunk sure swan swap swim
tail take tale talk tall tame tank tape task team tear tell tend tent term test than that them then they
thin this tide tidy tile till time tint tiny tire toad told toll tone took tool torn toss tour town trap
tray tree trim trip true tube tuck tune turn twin type
unit upon used
vane vase vast vent verb very vest view vine vote
wade wage wait wake walk wall wand want warm warn wash wave weak wear weed week well went were west what
when whip wide wife wild will wind wing wink wipe wire wise wish with woke wolf wood wool word wore work
worm worn wrap
yard yarn year yell yolk your
zero zone zoom
`
  .split(/\s+/)
  .filter(Boolean);
